AbsenceEnum = (function() {
	return { 
		UNEXCUSED_FIRST: 1, 
		UNEXCUSED_MIDDLE: 2,
		UNEXCUSED_LAST: 3,
		EXPELLED_SINGLE: 4,
		EXPELLED_DAILY: 5,
		EXCUSED_PARENT: 101,
		EXCUSED_DOCTOR: 102,
		EXCUSED_HEAD: 103
	};
})();
